### ISSUE TITLE
Error: ENOENT: no such file or directory, open './vueapp/dist/index.html'

### ISSUE THREAD

**Issue by mengxifl** [aol/moloch#1087]
**Elasticsearch version**: elasticsearch:5.6.16

**Moloch version**: 1.8.0

**OS name and version**: docker centos 7  - host os is centos 7 

**How was Moloch built/installed:** build

**Provide logs, stack traces and steps to reproduce**:

Error: ENOENT: no such file or directory, open './vueapp/dist/index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at app.use (/data/moloch/viewer/viewer.js:7697:18)
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/data/moloch/node_modules/express/lib/router/index.js:317:13)
    at /data/moloch/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/data/moloch/node_modules/express/lib/router/index.js:335:12)
    at next (/data/moloch/node_modules/express/lib/router/index.js:275:10)
    at /data/moloch/viewer/viewer.js:329:3
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)

**Comment by awick** [comment]
Please answer the questions that were in the github issue template

**Comment by mengxifl** [comment]
I solve a problem i run this command

**Comment by awick** [comment]
You must run viewer from the viewer directory.  The included systemd and upstart scripts do this for you with `WorkingDirectory=/data/moloch/viewer` or `chdir /data/moloch/viewer`
