### ISSUE TITLE
cannot log in to a molochviewer

### ISSUE THREAD

**Issue by zsn9170** [aol/moloch#1147]
**Elasticsearch version**:5.6.0

**Moloch version**:1.8.0-1

**OS name and version**: Debian 9.9

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:
Fri, 09 Aug 2019 12:29:09 GMT - ESC[1mGETESC[0m ESC[33m/mv/1/eshealth.jsonESC[0m 200 467 bytes 3.246 ms
passwordSecret set in the [default] section can not decrypt information. You may need to re-add users if you've changed the secret. Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
at Decipher.final (crypto.js:183:26)
at Object.exports.store2ha1 (/data/moloch/viewer/config.js:96:12)
at /data/moloch/viewer/viewer.js:122:53
at exports.getUser (/data/moloch/viewer/db.js:421:5)
at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:329:9)
at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4935:19)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)

I updated molochviewer from 0.20 to 1.8.0 version. Then I encountered the above error.
The problem occurs within 2-3 days.

After molochviewer login: ERR_EMPTY_RESPONSE

Workaround: reset users password

Can anyone help me with this?

**Comment by zsn9170** [comment]
Thanks for the reply. I'll test it.

No. I upgraded from 0.20 to 1.1 version, and then to 1.8 version. I follow the various upgrade stats.
