### ISSUE TITLE
When using the S3 writer, pressing Ctrl+C hangs moloch-capture

### ISSUE THREAD

**Issue by fj604** [aol/moloch#1319]
**Elasticsearch version**:
7.1
**Moloch version**:
moloch-capture 2.1.0-GIT/v2.1.0-14-g021c148 session size=392 packet size=80 api=200

**OS name and version**:
Amazon Linux 2 (~= CentOS 7) - same issue observed on Ubuntu 18.10

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

**Provide logs, stack traces and steps to reproduce**:
When using the S3 writer, pressing Ctrl+C hangs moloch-capture with the following output:
```
^CNov 23 19:58:43 main.c:308 controlc(): Control-C
Nov 23 19:58:43 main.c:604 moloch_quit(): Quitting

```
strace output:

```
poll([{fd=3, events=POLLIN}], 1, 50)    = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 50)    = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 50)    = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 50)    = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
write(1, "Nov 23 19:57:49 main.c:308 contr"..., 49) = 49
rt_sigaction(SIGINT, {sa_handler=0x7fc1975fa420, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fc1975f7b50}, {sa_handler=0x425140, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fc1975f7b50}, 8) = 0
write(1, "Nov 23 19:57:49 main.c:604 moloc"..., 51) = 51
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
poll([{fd=3, events=POLLIN}], 1, 42)    = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 50)    = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 8)     = 0 (Timeout)
openat(AT_FDCWD, "/proc/net/dev", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(8, "Inter-|   Receive               "..., 1024) = 449
close(8)                                = 0
getsockopt(4, SOL_PACKET, PACKET_STATISTICS, {tp_packets=0{tp_drops=0}, [8]) = 0
futex(0x84aba0, FUTEX_WAIT_PRIVATE, 2, NULL
```

reader plugin:
`viewerPlugins=writer-s3/index.js
`

**Comment by fj604** [comment]
gdb output:
```
Thread 1 "moloch-capture" received signal SIGINT, Interrupt.
0x00007ffff5c0e029 in poll () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff5c0e029 in poll () from /lib64/libc.so.6
#1  0x0000000000491d19 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x26bb9d0, timeout=<optimized out>, context=0x1a44000) at gmain.c:4203
#2  g_main_context_iterate (context=0x1a44000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3897
#3  0x0000000000492072 in g_main_loop_run (loop=0x1a45200) at gmain.c:4098
#4  0x0000000000423456 in main (argc=<optimized out>, argv=<optimized out>) at main.c:817

```

**Comment by fj604** [comment]
```
^C
Thread 1 "moloch-capture" received signal SIGINT, Interrupt.
0x00007ffff5c0e029 in poll () from /lib64/libc.so.6
(gdb) thread apply all bt

Thread 9 (Thread 0x7fffc9ff4700 (LWP 7819)):
#0  0x00007ffff5c0e029 in poll () from /lib64/libc.so.6
#1  0x0000000000455a48 in pcap_wait_for_frames_mmap (handle=handle@entry=0x1a4d3a0) at ./pcap-linux.c:5018
#2  0x00000000004562c5 in pcap_read_linux_mmap_v3 (handle=0x1a4d3a0, max_packets=10000, callback=0x448300 <reader_libpcap_pcap_cb>, user=0x7fffc9ff32f0 "\360\062\377\311\377\177") at ./pcap-linux.c:5577
#3  0x00000000004481f3 in reader_libpcap_thread (posv=<optimized out>) at reader-libpcap.c:78
#4  0x00000000004aab6f in g_thread_proxy (data=0x1bd78f0) at gthread.c:784
#5  0x00007ffff5edd40b in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff5c17e7f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7fffe0d1b700 (LWP 7815)):
#0  0x00007ffff5ee361e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000044b66a in moloch_packet_thread (threadp=<optimized out>) at packet.c:843
#2  0x00000000004aab6f in g_thread_proxy (data=0x1bd78a0) at gthread.c:784
#3  0x00007ffff5edd40b in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff5c17e7f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fffe151c700 (LWP 7814)):
#0  0x00007ffff5ee361e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000044b66a in moloch_packet_thread (threadp=<optimized out>) at packet.c:843
#2  0x00000000004aab6f in g_thread_proxy (data=0x1bd7850) at gthread.c:784
#3  0x00007ffff5edd40b in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff5c17e7f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fffe2940700 (LWP 7813)):
#0  0x00007ffff5be862b in nanosleep () from /lib64/libc.so.6
#1  0x00007ffff5c10654 in usleep () from /lib64/libc.so.6
#2  0x0000000000427562 in moloch_db_stats_thread (threadp=<optimized out>) at db.c:2288
#3  0x00000000004aab6f in g_thread_proxy (data=0x1bd7800) at gthread.c:784
#4  0x00007ffff5edd40b in start_thread () from /lib64/libpthread.so.0
#5  0x00007ffff5c17e7f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7fe4880 (LWP 7808)):
#0  0x00007ffff5c0e029 in poll () from /lib64/libc.so.6
#1  0x0000000000491d19 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x26bb740, timeout=<optimized out>, context=0x1a44000) at gmain.c:4203
#2  g_main_context_iterate (context=0x1a44000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3897
#3  0x0000000000492072 in g_main_loop_run (loop=0x1a45200) at gmain.c:4098
#4  0x0000000000423456 in main (argc=<optimized out>, argv=<optimized out>) at main.c:817

```

**Comment by fj604** [comment]
Updated previous gdb output after catching it at the right point.

**Comment by fj604** [comment]
```
(gdb) thread apply all bt

Thread 5 (Thread 0x7fe2e134e700 (LWP 8999)):
#0  0x00007fe30d17e029 in poll () from /lib64/libc.so.6
#1  0x00000000004537aa in pcap_wait_for_frames_mmap (handle=handle@entry=0x3555380) at ./pcap-linux.c:5018
#2  0x0000000000453d95 in pcap_read_linux_mmap_v3 (handle=0x3555380, max_packets=10000, callback=0x4468b0 <reader_libpcap_pcap_cb>, user=0x7fe2e134d2f0 "\360\322\064\341\342\177") at ./pcap-linux.c:5577
#3  0x00000000004467ae in reader_libpcap_thread (posv=<optimized out>) at reader-libpcap.c:78
#4  0x00000000004a2c1f in g_thread_proxy (data=0x36dfcf0) at gthread.c:784
#5  0x00007fe30d44d40b in start_thread () from /lib64/libpthread.so.0
#6  0x00007fe30d187e7f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fe2f3fff700 (LWP 8994)):
#0  0x00007fe30d45361e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000449a32 in moloch_packet_thread (threadp=<optimized out>) at packet.c:843
#2  0x00000000004a2c1f in g_thread_proxy (data=0x36dfca0) at gthread.c:784
#3  0x00007fe30d44d40b in start_thread () from /lib64/libpthread.so.0
#4  0x00007fe30d187e7f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fe2f8a8c700 (LWP 8993)):
#0  0x00007fe30d45361e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000449a32 in moloch_packet_thread (threadp=<optimized out>) at packet.c:843
#2  0x00000000004a2c1f in g_thread_proxy (data=0x36dfc50) at gthread.c:784
#3  0x00007fe30d44d40b in start_thread () from /lib64/libpthread.so.0
#4  0x00007fe30d187e7f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fe2f9eb0700 (LWP 8992)):
#0  0x00007fe30d4562ad in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fe30d44fbfd in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x00007fe2e9146df3 in writer_s3_queue_length () at writer-s3.c:108
#3  0x0000000000426882 in moloch_db_update_stats (n=n@entry=0, sync=sync@entry=0) at db.c:1280
#4  0x0000000000427183 in moloch_db_stats_thread (threadp=<optimized out>) at db.c:2296
#5  0x00000000004a2c1f in g_thread_proxy (data=0x36dfc00) at gthread.c:784
#6  0x00007fe30d44d40b in start_thread () from /lib64/libpthread.so.0
#7  0x00007fe30d187e7f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fe30f557880 (LWP 8990)):
#0  0x00007fe30d4562ad in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fe30d44fbfd in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x00007fe2e9146df3 in writer_s3_queue_length () at writer-s3.c:108
#3  0x0000000000449d70 in moloch_packet_log (ses=ses@entry=0) at packet.c:1162
#4  0x000000000044c837 in moloch_packet_exit () at packet.c:2281
#5  0x0000000000423849 in moloch_quit_gfunc (user_data=<error reading variable: value has been optimized out>) at main.c:566
#6  0x000000000048bc33 in g_timeout_dispatch (source=source@entry=0x37069c0, callback=<optimized out>, user_data=<optimized out>) at gmain.c:4649
#7  0x000000000048b334 in g_main_dispatch (context=0x354c000) at gmain.c:3176
#8  g_main_context_dispatch (context=context@entry=0x354c000) at gmain.c:3829
#9  0x000000000048b686 in g_main_context_iterate (context=0x354c000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3902
#10 0x000000000048b938 in g_main_loop_run (loop=0x354d200) at gmain.c:4098
#11 0x000000000042333a in main (argc=<optimized out>, argv=<optimized out>) at main.c:817
(gdb)

```

**Comment by fj604** [comment]
The code hangs only with --debug option as the hang is in the logging statement.
