### ISSUE TITLE
connections API with large length parameter causes errors with multi viewer

### ISSUE THREAD

**Issue by mmguero** [aol/moloch#1395]
**Elasticsearch version**: 7.6.1

**Moloch version**: 2.2.3 and Master

**OS name and version**: Linux (Debian 10)

**How was Moloch built/installed:** easybutton in docker

**Provide logs, stack traces and steps to reproduce**:

1. rename attached file from `api-connections-multi-bug.txt` to `api-connections-multi-bug.t`
2. place `api-connections-multi-bug.t` in `tests` directory
3. run `./tests.pl --viewer --debug api-connections-multi-bug.t`

Output:

```
$ ./tests.pl --viewer --debug api-connections-multi-bug.t 
Initializing ES
WARNING elasticsearch health is 'yellow' instead of 'green', things may be broken

It is STRONGLY recommended that you stop ALL moloch captures and viewers before proceeding.  Use 'db.pl http://127.0.0.1:9200 backup' to backup db first.

There is 1 elastic search data node, if you expect more please fix first before proceeding.

Erasing
Creating


Finished
It is STRONGLY recommended that you stop ALL moloch captures and viewers before proceeding.  Use 'db.pl http://127.0.0.1:9200 backup' to backup db first.

There is 1 elastic search data node, if you expect more please fix first before proceeding.

Erasing
Creating


Finished
Loading tagger
{"_index":"tagger","_type":"file","_id":"ip.tagger1.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"host.tagger1.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"md5.tagger1.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"ip.tagger2.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":3,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"host.tagger2.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":4,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"md5.tagger2.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":5,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"email.tagger2.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":6,"_primary_term":1}
{"_index":"tagger","_type":"file","_id":"uri.tagger2.json","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":7,"_primary_term":1}
Connecting 127.0.0.1:8081
Success
Loading PCAP
../capture/moloch-capture  -c config.test.ini -n test -R pcap --flush --debug 2>&1 1>/tmp/moloch.capture
Starting viewer
Connecting 127.0.0.1:8123
Success
Connecting 127.0.0.1:8124
Success
Connecting 127.0.0.1:8125
Success
Connecting 127.0.0.1:8008
Success
Connecting 127.0.0.1:8200
Success
api-connections-multi-bug.t .. # No tests run!
api-connections-multi-bug.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
(node:133) UnhandledPromiseRejectionWarning: Error: Not Found
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at emitWarning (internal/process/promises.js:97:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:133) Error: Not Found
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:111:13)
    at emitWarning (internal/process/promises.js:104:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)

Test Summary Report
-------------------
api-connections-multi-bug.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.14 cusr  0.01 csys =  0.18 CPU)
Result: FAIL
```

Note that in a more realistic scenario (where you are actually getting output and comparing tests to known good) I think you do actually get good output despite the errors running the test. However, I also thing that something about this bug is leaving search request scrolls open, as running it a few times causes elasticsearch to start spitting out this:

```
"Caused by: org.elasticsearch.ElasticsearchException: Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.",
```

Removing the `length=` parameter from the test causes the bug to go away.

Found this while working on issue #1162 and talking to @awick and @31453 in the #moloch-dev channel on slack.

[api-connections-multi-bug.txt](https://github.com/aol/moloch/files/4348966/api-connections-multi-bug.txt)

**Comment by 31453** [comment]
Looks like this works now! 🎉
