### ISSUE TITLE
Error: ENOENT: no such file or directory, open './vueapp/dist/index.html'

### ISSUE THREAD

**Issue by mayantec** [aol/moloch#1460]
**Elasticsearch version**:
6.5.1

**Moloch version**:
Moloch 2.3.1

**OS name and version**:
Centos 7

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

**Provide logs, stack traces and steps to reproduce**:
Capture
[root@centos]# /data/moloch/bin/moloch-capture -n absocentos.new.enp0s8 -c /data/moloch/etc/config.ini
[...]([url](url))
...
5 800/162 0ms 51ms
May 29 11:15:40 http.c:390 moloch_http_curlm_check_multi_info(): 1/4 ASYNC 200 172.17.0.2:9200/stats/_doc/absocentos.new.enp0s8?version_type=external&version=237 800/160 0ms 51ms
May 29 11:15:42 http.c:390 moloch_http_curlm_check_multi_info(): 1/4 ASYNC 200 172.17.0.2:9200/stats/_doc/absocentos.new.enp0s8?version_type=external&version=238 800/159 0ms 50ms
May 29 11:15:43 http.c:390 moloch_http_curlm_check_multi_info(): 1/4 ASYNC 201 172.17.0.2:9200/dstats/_doc/absocentos.new.enp0s8-188-5 800/162 0ms 50ms
...
...

Viewer
[root@centos]# /data/moloch/bin/node /data/moloch/viewer/viewer.js -c /data/moloch/etc/config.ini
Express server listening on port 8005 in development mode
Fri, 29 May 2020 18:11:16 GMT - GET / 401 - bytes 3.255 ms
Fri, 29 May 2020 18:11:33 GMT soc GET / 302 60 bytes 21.520 ms
Error: ENOENT: no such file or directory, open './vueapp/dist/index.html'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at app.use (/data/moloch/viewer/viewer.js:9011:18)
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/data/moloch/node_modules/express/lib/router/index.js:317:13)
    at /data/moloch/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/data/moloch/node_modules/express/lib/router/index.js:335:12)
    at next (/data/moloch/node_modules/express/lib/router/index.js:275:10)
    at setCookie (/data/moloch/viewer/viewer.js:972:10)
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/data/moloch/node_modules/express/lib/router/index.js:317:13)
    at /data/moloch/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/data/moloch/node_modules/express/lib/router/index.js:335:12)
    at next (/data/moloch/node_modules/express/lib/router/index.js:275:10)
    at csp (/data/moloch/node_modules/helmet-csp/dist/index.js:60:13)
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)
Fri, 29 May 2020 18:11:33 GMT soc GET /sessions 500 - bytes 10.277 ms

**The error occurs when i open the GUI**

**Comment by awick** [comment]
you must run from the /data/moloch/viewer directory.
