### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by yanliang941225** [aol/moloch#1476]
[root@docker1 opt]# /data/moloch/bin/moloch_add_user.sh admin "Admin User" admin --admin
_http_outgoing.js:464
    throw err;
    ^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:223:12)
    at Object.request (http.js:42:10)
    at HttpConnector.request (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:182:23)
    at sendReqWithConnection (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:263:35)
    at Object.utils.applyArgs (/data/moloch/node_modules/elasticsearch/src/lib/utils.js:188:19)
    at wrapper (/data/moloch/node_modules/lodash/lodash.js:5193:19)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by awick** [comment]
Please fill out the template for bug reports, I'm guessing you entered a bad hostname
