### ISSUE TITLE
module.js:340\     throw err;\  while creating admin user - easybutton-singlehost.sh

### ISSUE THREAD

**Issue by Gulliverg** [aol/moloch#297]
HI,
At the end of the easybutton-singlehost.sh process i'm getting the following error.
MOLOCH: Adding user admin/admin\
\
module.js:340\
    throw err;\
          ^\
Error: Cannot find module 'iniparser'\
    at Function.Module._resolveFilename (module.js:338:15)\
    at Function.Module._load (module.js:280:25)\
    at Module.require (module.js:364:17)\
    at require (module.js:380:17)\
    at Object.<anonymous> (/data/moloch/viewer/config.js:27:14)\
    at Module._compile (module.js:456:26)\
    at Object.Module._extensions..js (module.js:474:10)\
    at Module.load (module.js:356:32)\
    at Function.Module._load (module.js:312:12)\
    at Module.require (module.js:364:17)\

When i try to add the user from the viewer folder with the following command i'm getting the same error.
root@moloch:/data/moloch/viewer# node addUser.js -c ../etc/config.ini admin "Admin" admin -admin

module.js:340
    throw err;
          ^
Error: Cannot find module 'iniparser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/moloch/viewer/config.js:27:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

The instillation of Moloch is on ubuntu 14.04.1 server.
Your help will be much appreciated.

Attached the easybutton-singlehost.sh output.

Please enter the following 'extra' attributes\
to be sent with your certificate request\
A challenge password []:\
An optional company name []:\
Signature ok\
subject=/C=US/ST=Virginia/L=Sterling/O=MolochTester/OU=MolochUnit/CN=moloch.test.com\
Getting Private key\
MOLOCH: Starting ElasticSearch\
time(seconds)        unlimited\
file(blocks)         unlimited\
data(kbytes)         unlimited\
stack(kbytes)        8192\
coredump(blocks)     0\
memory(kbytes)       unlimited\
locked memory(kbytes) 64\
process              192723\
nofiles              128000\
vmemory(kbytes)      unlimited\
locks                unlimited\
Error occurred during initialization of VM\
Too small initial heap\
MOLOCH: Building database\
It is STRONGLY recommended that you stop ALL moloch captures and viewers before proceeding.\
\
There is 1 elastic search data node, if you expect more please fix first before proceeding.\
\
This is a fresh Moloch install\
Erasing\
Creating\
Updating sessions mapping for 5 indices\
\
Finished.  Have fun!\
MOLOCH: Adding user admin/admin\
\
module.js:340\
    throw err;\
          ^\
Error: Cannot find module 'iniparser'\
    at Function.Module._resolveFilename (module.js:338:15)\
    at Function.Module._load (module.js:280:25)\
    at Module.require (module.js:364:17)\
    at require (module.js:380:17)\
    at Object.<anonymous> (/data/moloch/viewer/config.js:27:14)\
    at Module._compile (module.js:456:26)\
    at Object.Module._extensions..js (module.js:474:10)\
    at Module.load (module.js:356:32)\
    at Function.Module._load (module.js:312:12)\
    at Module.require (module.js:364:17)\
MOLOCH: Starting viewer and capture\
MOLOCH: Complete use https://moloch:8005 to access.  You should also make the run_\* scripts in /data/moloch/bin run on start up and look at the config files in /data/moloch/etc\
nohup: appending output to \'e2\'80\'98nohup.out\'e2\'80\'99\
nohup: appending output to \'e2\'80\'98nohup.out\'e2\'80\'99}

**Comment by zhy0830** [comment]
I have met these problem,could you hepl me?
[root@localhost moloch-1.8.0]# /data/moloch/bin/moloch_add_user.sh admin "Admin User" THEPASSWORD --admin
Elastic search error { Error: [illegal_argument_exception] no write index is defined for alias [users]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 400,
  displayName: 'BadRequest',
  message:
   '[illegal_argument_exception] no write index is defined for alias [users]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index',
  path: '/users/user/admin',
  query: { refresh: 'true' },
  body:
   '{"userId":"admin","userName":"Admin User","passStore":"d5aebc251ec3186baadfc42935a01217fdad9ef40465a7ab2eaffe23cf0d75c513e24a5d83ed1b15be3672f55f61e856","enabled":true,"webEnabled":true,"headerAuthEnabled":false,"emailSearch":false,"createEnabled":true,"removeEnabled":false,"packetSearch":false,"welcomeMsgNum":0,"settings":{}}',
  statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no write index is defined for alias [users]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"}],"type":"illegal_argument_exception","reason":"no write index is defined for alias [users]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
