### ISSUE TITLE
Crash viewer when i stats tab open

### ISSUE THREAD

**Issue by OlesyaShell** [aol/moloch#306]
Hi! i have last version Moloch, node ES with other data (logstash). When i open stats tab - viewer can be crash.
/data/moloch/viewer/viewer.js:1213
        cpu: node.process.cpu.percent,
                             ^
TypeError: Cannot read property 'percent' of undefined
    at /data/moloch/viewer/viewer.js:1213:30
    at /data/moloch/viewer/node_modules/async/lib/async.js:592:17
    at done (/data/moloch/viewer/node_modules/async/lib/async.js:135:19)
    at /data/moloch/viewer/node_modules/async/lib/async.js:32:16
    at /data/moloch/viewer/node_modules/async/lib/async.js:589:21
    at /data/moloch/viewer/db.js:220:91
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:255:9)
    at checkRespForFailure (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:202:7)
    at HttpConnector.<anonymous> (/data/moloch/viewer/node_modules/elasticsearch/src/lib/connectors/http.js:148:7)
    at IncomingMessage.bound (/data/moloch/viewer/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
[3]+  Exit 8                  /data/moloch/bin/run_viewer.sh

**Comment by awick** [comment]
No new information, closing

**Comment by hadojae** [comment]
I have fixed this issue in the past by rebuilding the moloch es db via db.pl
