### ISSUE TITLE
WISE crashing

### ISSUE THREAD

**Issue by david-watson** [aol/moloch#373]
My WISE process periodically crashes with:

```
Sun, 03 May 2015 23:02:04 GMT POST /get - bytes 42 ms
Sun, 03 May 2015 23:02:05 GMT POST /get - bytes 39 ms
Sun, 03 May 2015 23:02:06 GMT POST /get - bytes 1 ms
[[23:02:07.504]] [LOG] ERROR undefined { type: 80,
  value: 'T /get HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Type: applicatio' } [TypeError: Property 'undefined' of object #<Object> is not a function]

/data/moloch/wiseService/node_modules/async/lib/async.js:54
        if (arr.map) {
               ^
TypeError: Cannot read property 'map' of undefined
    at _map (/data/moloch/wiseService/node_modules/async/lib/async.js:54:16)
    at _asyncMap (/data/moloch/wiseService/node_modules/async/lib/async.js:237:15)
    at Object.map (/data/moloch/wiseService/node_modules/async/lib/async.js:219:23)
    at /data/moloch/wiseService/wiseService.js:221:13
    at /data/moloch/wiseService/node_modules/async/lib/async.js:249:17
    at /data/moloch/wiseService/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/data/moloch/wiseService/node_modules/async/lib/async.js:46:24)
    at async.each (/data/moloch/wiseService/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/data/moloch/wiseService/node_modules/async/lib/async.js:248:13)
```
Restart, runs for a few days, dies in the same way again. Which causes huge capture.log files due to rapid logging of:

```
May  4 10:23:23 http.c:466 moloch_http_connect(): Connecting 0xe39f5a0 127.0.0.1 8081 0 0ms
May  4 10:23:23 http.c:266 moloch_http_read_cb(): ERROR: 127.0.0.1 0xedacc00:(nil) Receive Error: Error receiving data: Connection refused
May  4 10:23:23 http.c:466 moloch_http_connect(): Connecting 0xedacc00 127.0.0.1 8081 0 0ms
May  4 10:23:23 http.c:266 moloch_http_read_cb(): ERROR: 127.0.0.1 0xf75d000:(nil) Receive Error: Error receiving data: Connection refused
```
(easybutton install of latest code from git)

**Comment by awick** [comment]
* Do you have wise auto restarting, using upstart or inittab or whatever?  if not that will help with the capture errors

* What version are you using? I used to see this pre 0.11.5, I don't anymore, wonder if something got fixed.

**Comment by awick** [comment]
I think this is fixed, reopen if still an issue
