### ISSUE TITLE
Error:  stream.push() after EOF

### ISSUE THREAD

**Issue by PhilSchroeder** [aol/moloch#409]
Running 12.0-GIT from a June 5ish build.  Have seen a few of this one killing the viewer.

Trace: ERROR ITEM-HTTP [Error: stream.push() after EOF]
    at ItemHTTPStream.<anonymous> (/data/moloch/viewer/decode.js:761:15)
    at ItemHTTPStream.emit (events.js:117:20)
    at readableAddChunk (_stream_readable.js:147:14)
    at ItemHTTPStream.Readable.push (_stream_readable.js:127:10)
    at ItemHTTPStream.Transform.push (_stream_transform.js:140:32)
    at HTTPParser.ItemHTTPStream.onBody (/data/moloch/viewer/decode.js:481:21)
    at ItemHTTPStream._process (/data/moloch/viewer/decode.js:541:41)
    at async.each.self._itemTransform.items (/data/moloch/viewer/decode.js:61:14)
    at /data/moloch/viewer/node_modules/async/lib/async.js:162:20
    at /data/moloch/viewer/node_modules/async/lib/async.js:230:13

TypeError: Cannot read property 'client' of undefined
    at HTTPParser.ItemHTTPStream.onBody (/data/moloch/viewer/decode.js:481:39)
    at ItemHTTPStream._process (/data/moloch/viewer/decode.js:541:41)
    at async.each.self._itemTransform.items (/data/moloch/viewer/decode.js:61:14)
    at /data/moloch/viewer/node_modules/async/lib/async.js:162:20
    at /data/moloch/viewer/node_modules/async/lib/async.js:230:13
    at _arrayEach (/data/moloch/viewer/node_modules/async/lib/async.js:81:9)
    at _each (/data/moloch/viewer/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (/data/moloch/viewer/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (/data/moloch/viewer/node_modules/async/lib/async.js:206:22)
    at ItemHTTPStream.ItemTransform._transform (/data/moloch/viewer/decode.js:60:13)
    at ItemHTTPStream.Transform._read (_stream_transform.js:179:10)

**Comment by awick** [comment]
closing since an old version, open new issue if it still happens.
