### ISSUE TITLE
viewer can't find module jade

### ISSUE THREAD

**Issue by zetan503** [aol/moloch#447]
Hi, I got capture working, but viewer is a problem.
Oracle Linux 7.1

#./run.sh
+ cd /vm/moloch/viewer
+ export NODE_ENV=production
+ NODE_ENV=production
+ exec /bin/node /vm/moloch/viewer/viewer.js -c /vm/moloch/etc/config.ini
Express server listening on port 8443 in production mode
Tue, 08 Mar 2016 22:42:08 GMT test.user GET / 500 22 bytes 30.060 ms
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new View (/usr/lib/node_modules/express/lib/view.js:78:30)
    at EventEmitter.render (/usr/lib/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/usr/lib/node_modules/express/lib/response.js:961:7)
    at app.get.res.render.user (/vm/moloch/viewer/viewer.js:658:7)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/express/lib/router/route.js:131:13)

/vm/moloch/viewer/node_modules/ contains

async        elasticsearch  fs-ext     keep-alive-agent  morgan    passport-http  serve-favicon
body-parser  etc            iniparser  method-override   multer    peek-stream    stylus
compression  express        **jade**       moment            passport  png            through2

Ran npm update from viewer dir, no change.

node --version
v0.10.43

**Comment by awick** [comment]
try rm -r node_modules and running npm install again.  If that doesn't fix it post the output of npm ls

**Comment by zetan503** [comment]
Thank you that fixed the problem. Moloch lives!
