### ISSUE TITLE
deltaDropped out of range

### ISSUE THREAD

**Issue by zetan503** [aol/moloch#448]
Ran capture/viewer for 8 hours, getting good data, 1.2T captured so far.
I noticed the elastic search log is spewing this exception

Any ideas how to fix it?

```
[2016-03-09 13:49:48,976][DEBUG][action.index             ] [moloch-server] [stats][0], node[-cmtwNcHTqygaccAWKWa7A], [P], s[STARTED]: Failed to execute [index {[stats][stat][moloch-server], source[{"hostname": "moloch-server", "currentTime": 1457531384, "freeSpaceM": 32576615, "monitoring": 2480392, "memory": 13127835648, "cpu": 4709, "diskQueue": 23, "totalPackets": 494754737, "totalK": 389534373, "totalSessions": 118624216, "totalDropped": 122135463, "deltaPackets": 39423, "deltaBytes": 30183560, "deltaSessions": 10157, "deltaDropped": 18446744069419832031, "deltaMS": 2081}]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [deltaDropped]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:493)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:192)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Numeric value (18446744069419832031) out of range of long (-9223372036854775808 - 9223372036854775807)
 at [Source: [B@53f2b5ce; line: 1, column: 371]
        at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at org.elasticsearch.common.jackson.core.base.ParserBase.reportOverflowLong(ParserBase.java:1003)
        at org.elasticsearch.common.jackson.core.base.ParserBase.convertNumberToLong(ParserBase.java:894)
        at org.elasticsearch.common.jackson.core.base.ParserBase.getLongValue(ParserBase.java:674)
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.doLongValue(JsonXContentParser.java:173)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:147)
        at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:288)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:239)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
        ... 12 more
```

**Comment by awick** [comment]
What version of moloch and es?

**Comment by zetan503** [comment]
ElasticSearch 1.7.3
moloch v0.12.3-GIT

**Comment by zetan503** [comment]
Capture is logging a lot of drops

Mar 10 22:28:36 http.c:297 moloch_http_curlm_check_multi_info(): 500/30 ASYNC 200 http://127.0.0.1:9200/_bulk 299007/46039 0ms 117645ms
Mar 10 22:28:36 http.c:297 moloch_http_curlm_check_multi_info(): 499/30 ASYNC 200 http://127.0.0.1:9200/_bulk 298082/48745 0ms 48960ms
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 298902 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 297878 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 299291 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 298611 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 292439 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 298687 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 298649 queue 501 is too big
Mar 10 22:28:36 http.c:493 moloch_http_send(): ERROR - Dropping request /_bulk of size 299119 queue 501 is too big
Mar 10 22:28:36 http.c:297 moloch_http_curlm_check_multi_info(): 501/30 ASYNC 200 http://127.0.0.1:9200/_bulk 298691/49237 0ms 180409ms
Mar 10 22:28:36 http.c:297 moloch_http_curlm_check_multi_info(): 500/30 ASYNC 200 http://127.0.0.1:9200/_bulk 297995/46900 0ms 54334ms


Is my network card getting overrun? it is a busy circuit.

**Comment by awick** [comment]
If _bulk is failing that means your elasticsearch is failing.  You probably shouldn't have it on the same host if you have a busy circuit.
