### ISSUE TITLE
Node-viewer crashes while expanding pcap

### ISSUE THREAD

**Issue by gkazimiarovich** [aol/moloch#456]
On a multi-host setup, with single ES cluster, node-viewer crashes after opening several pcaps that are generated on viewer's host. 

moloch v0.12.3-GIT
ES cluster 1.7.3

viewer.log output:

TypeError: Cannot read property 'client' of undefined
    at HTTPParser.ItemHTTPStream.onBody (/data/moloch/viewer/decode.js:485:39)
    at ItemHTTPStream._process (/data/moloch/viewer/decode.js:545:41)
    at async.each.self._itemTransform.items (/data/moloch/viewer/decode.js:61:14)
    at /data/moloch/viewer/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/data/moloch/viewer/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/data/moloch/viewer/node_modules/async/lib/async.js:209:22)
    at ItemHTTPStream.ItemTransform._transform (/data/moloch/viewer/decode.js:60:13)
    at ItemHTTPStream.Transform._read (_stream_transform.js:179:10)
    at ItemHTTPStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)

Another point that may be relevant: other hosts' pcaps return "Couldn't connect to remote viewer, only displaying SPI data". HTTPS have been disabled for troubleshooting, with commenting out certFile, keyFile and caTrustFile properties.

Any thought on the issue are greatly appreciated

**Comment by gkazimiarovich** [comment]
Upgraded to moloch v 0.15.0, ES 2.3.3.
