### ISSUE TITLE
BytesRefHash$MaxBytesLengthExceededException errors

### ISSUE THREAD

**Issue by josh-lane** [aol/moloch#458]
**Elasticsearch version**:  ES 1.7.3

**Moloch version**:  0.12.1

**OS name and version**:  Ubuntu 12.04.5

**Provide logs, stack traces and steps to reproduce**:  Sending Moloch captures to ES in normal operation and see multiple errors like this:

java.lang.IllegalArgumentException: Document contains at least one immense term in field="rawus" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[-removed-]...', original message: bytes can be at most 32766 in length; got 41548
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:687)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:465)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1526)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1252)
        at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:432)
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:364)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:511)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:413)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 41548
        at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)
        at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:151)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:663)

Some are nearly twice the max value shown.

**Comment by awick** [comment]
Seems to be working for me, can you reopen if you see issues after upgrading.

**Comment by stoomart** [comment]
Elasticsearch version: 2.4

Moloch version: 0.17.1

OS name and version: CentOS 7.3.1611 x86_64

Provide logs, stack traces and steps to reproduce: I've seen the same message in the ES logs 4 times this week, which are followed by Moloch's ES queue filling up and requests being dropped.

`java.lang.IllegalArgumentException: Document contains at least one immense term in field="rawus" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[47, 47, 98, 97, 116, 115, 46, 118, 105, 100, 101, 111, 46, 121, 97, 104, 111, 111, 46, 99, 111, 109, 47, 112, 63, 116, 61, 48, 46, 55]...', original message: bytes can be at most 32766 in length; got 57428
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:692)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:365)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:321)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
	at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:527)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:454)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:601)
	at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:648)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 57428
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:150)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:682)
	... 24 more`
