### ISSUE TITLE
viewer.js aggregations error shuts down viewer

### ISSUE THREAD

**Issue by PhilSchroeder** [aol/moloch#479]
**Elasticsearch version**: ES2.2.0

**Moloch version**:     moloch v0.14.1-GIT

**OS name and version**:  Ubuntu Server 14.04.4 

**Provide logs, stack traces and steps to reproduce**:
This has been happening more and more frequently; I'll find that the viewer has died, and the logs show:

```
Tue, 31 May 2016 19:34:20 GMT USER ^[[1mGET^[[0m ^[[33m/unique.txt?date=-1&expression=http.uri%3D%3Dhttp.uri%3D%3D%22%2Fsms*&autocomplete=true&field=us^[[0m 200 - bytes 294565.507 ms

/data/moloch/viewer/viewer.js:2642
        async.forEachSeries(result.aggregations.field.buckets, eachCb, functio
                                  ^
TypeError: Cannot read property 'aggregations' of undefined
    at /data/moloch/viewer/viewer.js:2642:35
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:312:9)
    at /data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:340:7
    at null.<anonymous> (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:369:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```
OR (more frequently):

```
Mon, 16 May 2016 19:11:19 GMT USER GET /unique.txt?date=-1&expression=http.uri%3D%3Dhttp.uri%3D%3D%22%2F%22*&autocomplete=true&field=us 200 - bytes 218347.085 ms
sessions.json query {"from":"0","size":100,"query":{"filtered":{"query":{"match_all":{}},"filter":{"bool":{"must":[{"bool":{"must":[{"query":{"wildcard":{"rawus":"/?f=*"}}},{"query":{"wildcard":{"rawus":"*&a=*"}}}]}},{"query":{"wildcard":{"rawus":"*&cd=*"}}}]}}}},"aggregations":{"mapG1":{"terms":{"field":"g1","size":1000,"min_doc_count":1}},"mapG2":{"terms":{"field":"g2","size":1000,"min_doc_count":1}},"dbHisto":{"histogram":{"field":"lp","interval":3600,"min_doc_count":1},"aggregations":{"db":{"sum":{"field":"db"}},"pa":{"sum":{"field":"pa"}}}}},"sort":[{"fpd":{"order":"asc"}}],"_source":["pr","ro","db","db1","db2","fp","lp","a1","p1","a2","p2","pa","pa1","pa2","by","by1","by2","no","us","g1","g2","esub","esrc","edst","efn","dnsho","tls","ircch","tipv61-term","tipv62-term"]}
unique aggregations sessions-* {"from":0,"size":0,"query":{"filtered":{"query":{"match_all":{}}}},"aggregations":{"field":{"terms":{"field":"us","size":1000}}}}

/data/moloch/viewer/viewer.js:2638
        async.forEachSeries(result.aggregations.field.buckets, eachCb, functio
                                  ^
TypeError: Cannot read property 'aggregations' of undefined
    at /data/moloch/viewer/viewer.js:2638:35
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:312:9)
    at /data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:340:7
    at null.<anonymous> (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:369:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

**Comment by awick** [comment]
I think its fixed, let me know

**Comment by awick** [comment]
please reopen if you still have issues
