### ISSUE TITLE
Viewer dies with undefined client TypeError

### ISSUE THREAD

**Issue by PhilSchroeder** [aol/moloch#522]
**Elasticsearch version**:2.2.0

**Moloch version**:0.14.2-GIT

**OS name and version**:ubuntu 14.04.4

**Provide logs, stack traces and steps to reproduce**:

We keep getting this viewer-killer when trying to expand certain entries:

TypeError: Cannot read property 'client' of undefined
    at HTTPParser.ItemHTTPStream.onBody (/data/moloch/viewer/decode.js:485:39)
    at ItemHTTPStream._process (/data/moloch/viewer/decode.js:545:41)
    at async.each.self._itemTransform.items (/data/moloch/viewer/decode.js:61:14)
    at /data/moloch/viewer/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/data/moloch/viewer/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/data/moloch/viewer/node_modules/async/lib/async.js:209:22)
    at ItemHTTPStream.ItemTransform._transform (/data/moloch/viewer/decode.js:60:13)
    at ItemHTTPStream.Transform._read (_stream_transform.js:179:10)
    at ItemHTTPStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)  

I can provide steps to reproduce, but only on our system.  Please contact me if you need.

**Comment by whitetiger21022014** [comment]
After decryption SSL - 443, I capture to PCAP, then import PCAP to Moloch
When expanding some sesssions, only some sesssion has that problem as below, and run_viewer service stopped
Thanks,



ES: 2.4.0
Moloch versio: moloch v0.16.1-GIT, installed from github 19 Oct, 2016
OS: Ubuntu: 16.04.1 TLS


Wed, 19 Oct 2016 08:15:29 GMT admin GET /Netsnake-001/161017-VtWlEcLtji1HH5qYDGMnnH9x/sessionDetail?line=false&image=true&gzip=true&decode=%7B%7D&ts=true&base=natural 200 - bytes 779.262 ms
Wed, 19 Oct 2016 08:15:31 GMT admin GET /Netsnake-001/raw/161017-VtWlEcLtji1HH5qYDGMnnH9x.png?type=src 200 1980 bytes 17.037 ms
/data/moloch/viewer/decode.js:286
  return (item.data.length >= 4 && item.data.slice(0,4).toString().match(/(HELO|EHLO)/));
              ^

TypeError: Cannot read property 'data' of undefined
    at ItemSMTPStream._shouldProcess (/data/moloch/viewer/decode.js:286:15)
    at ItemSMTPStream.ItemTransform._transform (/data/moloch/viewer/decode.js:58:14)
    at ItemSMTPStream.Transform._read (_stream_transform.js:167:10)
    at ItemSMTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at ItemSMTPStream.Writable.write (_stream_writable.js:214:11)
    at ItemHTTPStream.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at ItemHTTPStream.emit (events.js:169:7)


Wed, 19 Oct 2016 08:26:47 GMT - GET /images/details_close.png 304 - bytes 0.511                                                                                         ms
Wed, 19 Oct 2016 08:26:47 GMT admin GET /Netsnake-001/161017-VtWdUt7SoU5OI7TBhh4                                                                                        Vnyxg/sessionDetail?line=false&image=true&gzip=true&decode=%7B%7D&ts=true&base=n                                                                                        atural 200 - bytes 614.361 ms
Wed, 19 Oct 2016 08:27:04 GMT admin GET /Netsnake-001/161017-VtXGbkLyAGVDg4F_PLz                                                                                        9UoUl/sessionDetail?line=false&image=true&gzip=true&decode=%7B%7D&ts=true&base=n                                                                                        atural 200 - bytes 551.517 ms
Wed, 19 Oct 2016 08:27:08 GMT admin GET /Netsnake-001/161017-VtV4vZ192tdCK5mC9l5                                                                                        yTE7E/sessionDetail?line=false&image=true&gzip=true&decode=%7B%7D&ts=true&base=n                                                                                        atural 200 - bytes 452.404 ms
/data/moloch/viewer/decode.js:485
    this.httpstream.push({client: item.client, ts: item.ts, data: buf.slice(0, s                                                                                        tart)});
                                      ^
-----------------------------------------------------------------------------------------
TypeError: Cannot read property 'client' of undefined
    at HTTPParser.ItemHTTPStream.onBody (/data/moloch/viewer/decode.js:485:39)
    at ItemHTTPStream._process (/data/moloch/viewer/decode.js:556:41)
    at async.each.self._itemTransform.items (/data/moloch/viewer/decode.js:61:14                                                                                        )
    at /data/moloch/viewer/node_modules/async/dist/async.js:3205:16
    at eachOfArrayLike (/data/moloch/viewer/node_modules/async/dist/async.js:108                                                                                        9:9)
    at eachOf (/data/moloch/viewer/node_modules/async/dist/async.js:1139:5)
    at Object.eachLimit (/data/moloch/viewer/node_modules/async/dist/async.js:32                                                                                        69:3)
    at ItemHTTPStream.ItemTransform._transform (/data/moloch/viewer/decode.js:60                                                                                        :13)
    at ItemHTTPStream.Transform._read (_stream_transform.js:167:10)
    at ItemHTTPStream.Transform._write (_stream_transform.js:155:12)

**Comment by awick** [comment]
Possible to get a sample pcap?  Send to andywick @ gmail

**Comment by whitetiger21022014** [comment]
I just sent pcap to your email. Many thanks Andy Wick

**Comment by awick** [comment]
So shouldn't crash with above commit, however it won't decode well (if at all.)  These seems to be caused most commonly by truncated packets.

**Comment by whitetiger21022014** [comment]
Thank for your support
