### ISSUE TITLE
Every time the same mistake

### ISSUE THREAD

**Issue by syi2005s** [aol/moloch#577]
MOLOCH: Adding user admin/admin
/data/moloch/viewer/config.js:211
    process.setgid(group);
            ^

Error: setgid group id does not exist
    at Error (native)
    at dropPrivileges (/data/moloch/viewer/config.js:211:13)
    at Object.<anonymous> (/data/moloch/viewer/config.js:300:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/moloch/viewer/addUser.js:25:14)
MOLOCH: Starting viewer and capture
MOLOCH: Complete use https://ubuntu:8005 to access.  You should also make the run_* scripts in /data/moloch/bin run on start up and look at the config files in /data/moloch/etc
nohup: nohup: appending output to 'nohup.out'
appending output to 'nohup.out'

**Comment by awick** [comment]
Please fill in the bug report template when adding an issue in the future.

easybutton is no longer supported, try the rpms/debs.

edit your config.ini and change to dropGroup=daemon if you want to make work.
