### ISSUE TITLE
moloch services fail to start after rebooting on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by mikoim** [aol/moloch#588]
**Elasticsearch version**: 2.4.4

**Moloch version**: 0.17.0

**OS name and version**: Ubuntu 16.04.1 (amd64)

**How was Moloch built/installed:** deb

```bash
# Install Oracle Java
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer

# Install elasticsearch
dpkg -i elasticsearch-2.4.4.deb
systemctl enable elasticsearch.service
systemctl start elasticsearch.service

# Install moloch
dpkg -i moloch_0.17.0-1_amd64.deb
apt-get install -f
/data/moloch/bin/Configure
/data/moloch/db/db.pl http://localhost:9200 init
/data/moloch/bin/moloch_add_user.sh admin admin admin --admin
systemctl enable molochviewer.service molochcapture.service
systemctl start molochviewer.service molochcapture.service
```

**Provide logs, stack traces and steps to reproduce**:

Immediately after installation, it works normally. But rebooting system, moloch services failed to start. I think that it's caused by slow starting elasticsearch. I have introduced the following workarounds. Is there another method to solve this problem?

## Workaround

**Changelogs**

1. Add elasticsearch.service to After/Requires
1. Add sleep command to ExecStart

```
# /etc/systemd/system/molochviewer.service
[Unit]
Description=Moloch Viewer
After=network.target elasticsearch.service
Requires=network.target elasticsearch.service

[Service]
Type=simple
Restart=always
StandardOutput=tty
ExecStart=/bin/sh -c 'sleep 5 && /data/moloch/bin/node viewer.js -c /data/moloch/etc/config.ini >> /data/moloch/logs/viewer.log 2>&1'
WorkingDirectory=/data/moloch/viewer

[Install]
WantedBy=multi-user.target
```

```
# /etc/systemd/system/molochcapture.service
[Unit]
Description=Moloch Capture
After=network.target elasticsearch.service
Requires=network.target elasticsearch.service

[Service]
Type=simple
Restart=always
StandardOutput=tty
ExecStartPre=-/sbin/ethtool -G ens3 rx 4096 tx 4096
ExecStartPre=-/sbin/ethtool -K ens3 rx off tx off
ExecStartPre=-/sbin/ethtool -K ens3 sg off
ExecStartPre=-/sbin/ethtool -K ens3 tso off
ExecStartPre=-/sbin/ethtool -K ens3 ufo off
ExecStartPre=-/sbin/ethtool -K ens3 gso off
ExecStartPre=-/sbin/ethtool -K ens3 gro off
ExecStartPre=-/sbin/ethtool -K ens3 lro off
ExecStart=/bin/sh -c 'sleep 5 && /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini >> /data/moloch/logs/capture.log 2>&1'
WorkingDirectory=/data/moloch
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

## Logs

**/data/moloch/logs/capture.log**
```
Jan 24 15:51:52 main.c:595 main(): THREAD 0x7f05f630e780
Jan 24 15:51:52 main.c:163 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - ubuntu
Jan 24 15:51:52 config.c:184 moloch_config_int(): INFO: Reseting pcapWriteSize since 262143 is less then the min 262144
Jan 24 15:51:52 main.c:573 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Jan 24 15:51:52 http.c:194 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jan 24 15:51:52 db.c:1713 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jan 24 15:51:53 main.c:595 main(): THREAD 0x7fae28059780
Jan 24 15:51:53 main.c:163 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - ubuntu
Jan 24 15:51:53 config.c:184 moloch_config_int(): INFO: Reseting pcapWriteSize since 262143 is less then the min 262144
Jan 24 15:51:53 main.c:573 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Jan 24 15:51:53 http.c:194 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jan 24 15:51:53 db.c:1713 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jan 24 15:51:53 main.c:595 main(): THREAD 0x7f8297f64780
Jan 24 15:51:53 main.c:163 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - ubuntu
Jan 24 15:51:53 config.c:184 moloch_config_int(): INFO: Reseting pcapWriteSize since 262143 is less then the min 262144
Jan 24 15:51:53 main.c:573 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Jan 24 15:51:53 http.c:194 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jan 24 15:51:53 db.c:1713 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jan 24 15:51:53 main.c:595 main(): THREAD 0x7f6c61107780
Jan 24 15:51:53 main.c:163 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - ubuntu
Jan 24 15:51:53 config.c:184 moloch_config_int(): INFO: Reseting pcapWriteSize since 262143 is less then the min 262144
Jan 24 15:51:53 main.c:573 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Jan 24 15:51:53 http.c:194 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jan 24 15:51:53 db.c:1713 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jan 24 15:51:54 main.c:595 main(): THREAD 0x7f1d4028b780
Jan 24 15:51:54 main.c:163 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - ubuntu
Jan 24 15:51:54 config.c:184 moloch_config_int(): INFO: Reseting pcapWriteSize since 262143 is less then the min 262144
Jan 24 15:51:54 main.c:573 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Jan 24 15:51:54 http.c:194 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jan 24 15:51:54 db.c:1713 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
```

**/data/moloch/logs/viewer.log**
```
Elasticsearch WARNING: 2017-01-24T06:51:58Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-24T06:51:58Z
  No living connections

{ [Error: No Living connections] message: 'No Living connections' } undefined
/data/moloch/viewer/db.js:73
    if (data.version.number.match(/^(2.[0-3]|1|0)/)) {
            ^

TypeError: Cannot read property 'version' of undefined
    at /data/moloch/viewer/db.js:73:13
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:308:9)
    at sendReqWithConnection (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:207:7)
    at next (/data/moloch/viewer/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
Elasticsearch ERROR: 2017-01-24T06:55:46Z
  Error: Request error, retrying
  GET http://localhost:9200/ => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/data/moloch/viewer/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/data/moloch/viewer/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/data/moloch/viewer/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:269:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1267:8)

Elasticsearch WARNING: 2017-01-24T06:55:46Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-24T06:55:46Z
  No living connections

{ [Error: No Living connections] message: 'No Living connections' } undefined
/data/moloch/viewer/db.js:73
    if (data.version.number.match(/^(2.[0-3]|1|0)/)) {
            ^

TypeError: Cannot read property 'version' of undefined
    at /data/moloch/viewer/db.js:73:13
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:308:9)
    at sendReqWithConnection (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:207:7)
    at next (/data/moloch/viewer/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
```

**Comment by awick** [comment]
It is not recommended that ES and capture be on the same hosts, so definitely can't add the requires elasticsearch.

The sleep is an option, but on a properly setup system it would delay capturing by 5 seconds.  You could move it after I guess.  (BTW there is a RestartSec= setting so you don't have to do a sleep, although would need to double check that it is AFTER a failure)

Could probably mess around with   StartLimitInterval= or  StartLimitBurst= but I have no experience with those.

Seems like this could just be an FAQ entry.
