### ISSUE TITLE
Viewer build issue with png and node-gyp

### ISSUE THREAD

**Issue by LaramieSmile** [aol/moloch#609]
I'm trying to build the current moloch updates on a system currently running v0.16.1 but I'm running into issues during the Viewer build.  Everything has gone smoothly with previews builds.  Been running Moloch on this box for probably over a year now.

```
> png@3.0.3 install /root/manual_installs/moloch/viewer/node_modules/png
> node-gyp rebuild

make: Entering directory '/root/manual_installs/moloch/viewer/node_modules/png/build'
  CXX(target) Release/obj.target/png/src/common.o
  CXX(target) Release/obj.target/png/src/png_encoder.o
  CXX(target) Release/obj.target/png/src/png.o
../src/png.cpp: In member function ‘v8::Handle<v8::Value> Png::PngEncodeSync()’:
../src/png.cpp:33:71: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
     Local<Value> buf_val = Local<Object>::New(isolate, persistent())->GetHiddenValue(String::NewFromUtf8(isolate, "buffer"));
                                                                       ^
../src/png.cpp: In static member function ‘static void Png::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/png.cpp:155:53: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
     Local<Object>::New(isolate, png->persistent())->SetHiddenValue(String::NewFromUtf8(isolate, "buffer"), args[0]);
                                                     ^
../src/png.cpp: In static member function ‘static void Png::UV_PngEncodeAfter(uv_work_t*)’:
../src/png.cpp:214:14: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch; // don't quite see the necessity of this
              ^
In file included from /root/.node-gyp/7.1.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.1.0/include/node/node.h:42,
                 from ../src/common.h:4,
                 from ../src/png.cpp:3:
/root/.node-gyp/7.1.0/include/node/v8.h:7015:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/root/.node-gyp/7.1.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/png.cpp:219:33: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
         FatalException(try_catch);
                                 ^
In file included from ../src/common.h:4:0,
                 from ../src/png.cpp:3:
/root/.node-gyp/7.1.0/include/node/node.h:299:29: note: declared here
                 inline void FatalException(const v8::TryCatch& try_catch) {
                             ^
/root/.node-gyp/7.1.0/include/node/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/png.cpp: In static member function ‘static void Png::PngEncodeAsync(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/png.cpp:264:76: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
     Local<Value> buf_val = Local<Object>::New(isolate, png->persistent())->GetHiddenValue(String::NewFromUtf8(isolate, "buffer"));
                                                                            ^
png.target.mk:93: recipe for target 'Release/obj.target/png/src/png.o' failed
make: *** [Release/obj.target/png/src/png.o] Error 1
make: Leaving directory '/root/manual_installs/moloch/viewer/node_modules/png/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/manual_installs/moloch/viewer/node_modules/png
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: png@3.0.3 (node_modules/png):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: png@3.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

I've removed the node_modules folder and tried again with no joy.  Any pointers would be much appreciated.

**Comment by awick** [comment]
We haven't done any testing with node 7, node 4.6 is required for now.

That said png is an optional dep, so it should work anyway.
