### ISSUE TITLE
Cannot export more than 9999 entries to PCAP

### ISSUE THREAD

**Issue by sitbk** [aol/moloch#697]
**Elasticsearch version**: 5.3.1

**Moloch version**: 18.x, 19 nightly

**OS name and version**: Debian 8

**How was Moloch built/installed:** DEB

**Provide logs, stack traces and steps to reproduce**: Exporting more than 9999 (exact) results in an "Unable to Connect" or "Connection was reset" error in Firefox. I attempted to increase the index.max_result_window in the sessions template, followed by removing the indices and letting them rebuild. I still receive the error. See below for my viewer log:

> TypeError: Cannot read property 'hits' of undefined
>     at getMoreUntilDone (/data/moloch-nightly/viewer/db.js:178:75)
>     at respond (/data/moloch-nightly/viewer/node_modules/elasticsearch/src/lib/transport.js:308:9)
>     at checkRespForFailure (/data/moloch-nightly/viewer/node_modules/elasticsearch/src/lib/transport.js:248:7)
>     at HttpConnector.<anonymous> (/data/moloch-nightly/viewer/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
>     at IncomingMessage.wrapper (/data/moloch-nightly/viewer/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:923:12)
>     at nextTickCallbackWith2Args (node.js:511:9)
>     at process._tickCallback (node.js:425:17)
> Express server listening on port 8005 in development mode
> Thu, 01 Jun 2017 10:13:38 GMT admin [1mGET [0m [33m/?date=1 [0m 302 74 bytes 37.140 ms
> Thu, 01 Jun 2017 10:13:38 GMT admin [1mGET [0m [33m/sessions?date=1 [0m 304 - bytes 421.284 ms
> Thu, 01 Jun 2017 10:13:38 GMT admin [1mGET [0m [33m/vendor.bundle.js [0m 304 - bytes 8.559 ms
> Thu, 01 Jun 2017 10:13:38 GMT admin [1mGET [0m [33m/app.bundle.js [0m 304 - bytes 3.136 ms
> Thu, 01 Jun 2017 10:13:39 GMT - [1mGET [0m [33m/eshealth.json [0m 200 455 bytes 8.009 ms
> Thu, 01 Jun 2017 10:13:39 GMT admin [1mGET [0m [33m/user/current [0m 304 - bytes 25.669 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/titleconfig [0m 304 - bytes 1.250 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/tableState/sessionsNew [0m 304 - bytes 4.427 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/user/settings [0m 304 - bytes 2.388 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/user/columns [0m 304 - bytes 1.974 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/molochclusters [0m 304 - bytes 1.841 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/user/views [0m 304 - bytes 2.528 ms
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/fields [0m 304 - bytes 1.523 ms
> sessions.json query {"from":0,"size":50,"query":{"bool":{"filter":[{"range":{"lp":{"gte":1496308420,"lte":1496312020}}}]}},"aggregations":{"mapG1":{"terms":{"field":"g1","size":1000,"min_doc_count":1}},"mapG2":{"terms":{"field":"g2","size":1000,"min_doc_count":1}},"dbHisto":{"histogram":{"field":"lp","interval":60,"min_doc_count":1},"aggregations":{"db":{"sum":{"field":"db"}},"pa":{"sum":{"field":"pa"}}}}},"sort":[{"fpd":{"order":"asc"}}],"_source":["pr","tipv61-term","tipv62-term","fp","lp","a1","g1","p1","a2","g2","p2","pa","db","by","no","us","esrc","edst","esub","efn","dnsho","tls.alt","ircch"]}
> Thu, 01 Jun 2017 10:13:40 GMT admin [1mGET [0m [33m/sessions.json?bounding=last&facets=1&fields=pr,tipv61-term,tipv62-term,fp,lp,a1,g1,p1,a2,g2,p2,pa,db,by,no,us,esrc,edst,esub,efn,dnsho,tls.alt,ircch&flatten=1&length=50&order=fp:asc&startTime=1496308420&stopTime=1496312020 [0m 200 - bytes 199.801 ms
> Thu, 01 Jun 2017 10:13:49 GMT - [1mGET [0m [33m/eshealth.json [0m 200 455 bytes 14.476 ms
> Thu, 01 Jun 2017 10:13:59 GMT - [1mGET [0m [33m/sessions.pcap/sessions.pcap?date=1&start=0&length=11134&segments=no [0m 401 - bytes 1.954 ms
> Thu, 01 Jun 2017 10:13:59 GMT - [1mGET [0m [33m/eshealth.json [0m 304 - bytes 0.805 ms
> /data/moloch-nightly/viewer/db.js:178
>           Array.prototype.push.apply(totalResults.hits.hits, response.hits.hits);
>                                                                           ^
> TypeError: Cannot read property 'hits' of undefined
>     at getMoreUntilDone (/data/moloch-nightly/viewer/db.js:178:75)
>     at respond (/data/moloch-nightly/viewer/node_modules/elasticsearch/src/lib/transport.js:308:9)
>     at checkRespForFailure (/data/moloch-nightly/viewer/node_modules/elasticsearch/src/lib/transport.js:248:7)
>     at HttpConnector.<anonymous> (/data/moloch-nightly/viewer/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
>     at IncomingMessage.wrapper (/data/moloch-nightly/viewer/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:923:12)
>     at nextTickCallbackWith2Args (node.js:511:9)
>     at process._tickCallback (node.js:425:17)
> Express server listening on port 8005 in development mode

**Comment by sitbk** [comment]
I ran 'curl -s 'localhost:9200/sessions*/_search?size=#####&pretty' replacing ##### with anything from 1000 to 20000 (the index.max_window_size I set). So the index.max_window_size change I made to the sessions template is reflected by this command, I can use it up to 20000 now. 20001 results in an error. However, using the Moloch viewer to export more than 9999 entries to PCAP still fails.
