### ISSUE TITLE
Unable to export to CSV

### ISSUE THREAD

**Issue by benjimons** [aol/moloch#799]
**Elasticsearch version**: 5.6.0

**Moloch version**: 0.50.0

**OS name and version**: Centos 7.4

**How was Moloch built/installed:**  RPM from molo.ch

**Provide logs, stack traces and steps to reproduce**:
When trying to export to CSV from the UI for the visible items only it fails with the below error

```
TypeError: req.query.fields.split is not a function
    at /data/moloch/viewer/viewer.js:3741:43
    at Layer.handle [as handle_request] (/data/moloch/viewer/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/moloch/viewer/node_modules/express/lib/router/route.js:137:13)
    at /data/moloch/viewer/viewer.js:758:12
    at Layer.handle [as handle_request] (/data/moloch/viewer/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/moloch/viewer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/data/moloch/viewer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/moloch/viewer/node_modules/express/lib/router/layer.js:95:5)
    at /data/moloch/viewer/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/data/moloch/viewer/node_modules/express/lib/router/index.js:335:12)
```

From this URI

```
Sun, 04 Feb 2018 08:12:02 GMT admin ESC[1mGETESC[0m ESC[33m/sessions.csv/sessions.csv?bounding=last&expression=ip.src+%3D%3D+192.168.0.1&facets=1&fields=pr,tipv
61-term,tipv62-term,fp,lp,a1,g1,p1,a2,g2,p2,pa,db,by,no,hat-term,http.method-term,xff,tcpflags.syn-ack,tcpflags.rst,tcpflags.urg,tcpflags.psh,tcpflags.syn,tcpflags.
fin,prot-term,http.statuscode,hpath,http.statuscode-cnt&flatten=1&interval=auto&length=500&order=fp:desc&start=0&startTime=1517644230&stopTime=1517730630&segments=no&fields=fp,lp,a1,g1,p1,a2,g2,p2,pa,db,by,no,us,esrc,edst,esub,efn,dnsho,tls.alt,ircchESC[0m 500 - bytes 11.013 ms
```

**Comment by awick** [comment]
Try using just one fields=
