### ISSUE TITLE
compile error (curl)

### ISSUE THREAD

**Issue by 2Belette** [aol/moloch#810]
Hi, 

During ./easybutton-build.sh I got this error:
```
version.c:(.text+0xa4): undefined reference to `psl_get_version'
http2.c:(.text+0x38): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x58): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x92): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x3c8): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x42f): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x624): undefined reference to `nghttp2_session_want_write'
http2.c:(.text+0x683): undefined reference to `nghttp2_priority_spec_init'
http2.c:(.text+0x70b): undefined reference to `nghttp2_submit_priority'
http2.c:(.text+0x717): undefined reference to `nghttp2_session_send'
http2.c:(.text+0x7ec): undefined reference to `nghttp2_session_del'
http2.c:(.text+0x863): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0xa6c): undefined reference to `nghttp2_submit_rst_stream'
http2.c:(.text+0xa75): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0xa9c): undefined reference to `nghttp2_session_get_remote_settings'
http2.c:(.text+0xab1): undefined reference to `nghttp2_session_get_remote_settings'
http2.c:(.text+0xbdb): undefined reference to `nghttp2_submit_rst_stream'
http2.c:(.text+0xbe2): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0xcae): undefined reference to `nghttp2_session_set_stream_user_data'
http2.c:(.text+0xd96): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0xdd2): undefined reference to `nghttp2_session_set_stream_user_data'
http2.c:(.text+0xe68): undefined reference to `nghttp2_session_want_read'
http2.c:(.text+0xe7c): undefined reference to `nghttp2_session_want_write'
http2.c:(.text+0xeba): undefined reference to `nghttp2_session_mem_recv'
http2.c:(.text+0xf42): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x10e5): undefined reference to `nghttp2_http2_strerror'
http2.c:(.text+0x11c1): undefined reference to `nghttp2_session_resume_data'
http2.c:(.text+0x11d8): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x1244): undefined reference to `nghttp2_session_resume_data'
http2.c:(.text+0x16e9): undefined reference to `nghttp2_submit_request'
http2.c:(.text+0x1733): undefined reference to `nghttp2_session_send'
http2.c:(.text+0x1768): undefined reference to `nghttp2_session_resume_data'
http2.c:(.text+0x1c34): undefined reference to `nghttp2_session_mem_recv'
http2.c:(.text+0x1c3e): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x1ecb): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x1f69): undefined reference to `nghttp2_session_callbacks_new'
http2.c:(.text+0x1f9d): undefined reference to `nghttp2_session_callbacks_set_send_callback'
http2.c:(.text+0x1fae): undefined reference to `nghttp2_session_callbacks_set_on_frame_recv_callback'
http2.c:(.text+0x1fbf): undefined reference to `nghttp2_session_callbacks_set_on_invalid_frame_recv_callback'
http2.c:(.text+0x1fd0): undefined reference to `nghttp2_session_callbacks_set_on_data_chunk_recv_callback'
http2.c:(.text+0x1fe1): undefined reference to `nghttp2_session_callbacks_set_before_frame_send_callback'
http2.c:(.text+0x1ff2): undefined reference to `nghttp2_session_callbacks_set_on_frame_send_callback'
http2.c:(.text+0x2003): undefined reference to `nghttp2_session_callbacks_set_on_frame_not_send_callback'
http2.c:(.text+0x2014): undefined reference to `nghttp2_session_callbacks_set_on_stream_close_callback'
http2.c:(.text+0x2025): undefined reference to `nghttp2_session_callbacks_set_on_begin_headers_callback'
http2.c:(.text+0x2036): undefined reference to `nghttp2_session_callbacks_set_on_header_callback'
http2.c:(.text+0x2047): undefined reference to `nghttp2_session_callbacks_set_error_callback'
http2.c:(.text+0x205b): undefined reference to `nghttp2_session_client_new'
http2.c:(.text+0x2067): undefined reference to `nghttp2_session_callbacks_del'
http2.c:(.text+0x2098): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x20b8): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x218f): undefined reference to `nghttp2_version'
http2.c:(.text+0x23ce): undefined reference to `nghttp2_session_set_stream_user_data'
http2.c:(.text+0x23fe): undefined reference to `nghttp2_submit_rst_stream'
http2.c:(.text+0x24e5): undefined reference to `nghttp2_pack_settings_payload'
http2.c:(.text+0x261a): undefined reference to `nghttp2_session_resume_data'
http2.c:(.text+0x288f): undefined reference to `nghttp2_submit_settings'
http2.c:(.text+0x28af): undefined reference to `nghttp2_session_set_local_window_size'
http2.c:(.text+0x2923): undefined reference to `nghttp2_session_upgrade'
http2.c:(.text+0x293b): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x2968): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x2998): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x29d2): undefined reference to `nghttp2_session_set_stream_user_data'
http2.c:(.text+0x2a16): undefined reference to `nghttp2_session_mem_recv'
http2.c:(.text+0x2a20): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x2a56): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x2a89): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x21c1): undefined reference to `nghttp2_http2_strerror'
cookie.c:(.text+0x1131): undefined reference to `psl_builtin'
cookie.c:(.text+0x114b): undefined reference to `psl_is_cookie_domain_acceptable'
```

I tried to configure curl with `--without-http2` or `--without-nghttp2` but still stuck with (only):

```
version.c:(.text+0xa4): undefined reference to `psl_get_version'
cookie.c:(.text+0x1131): undefined reference to `psl_builtin'
cookie.c:(.text+0x114b): undefined reference to `psl_is_cookie_domain_acceptable'
```

Any idea?

**Comment by awick** [comment]
Probably add `--without-libpsl`, any reason you aren't using the prebuilt?

**Comment by 2Belette** [comment]
I wish I could but my server OS is archlinux based and I haven't seen a prebuilt for it?

**Comment by awick** [comment]
did that change work?

**Comment by 2Belette** [comment]
Do you mean prebuilt would work on my os?

**Comment by awick** [comment]
no, I meant did you try also adding `--without-libpsl` to the 2 you already added.

**Comment by 2Belette** [comment]
Yep :) thanks! I hope that theses functions are not needed!
now I have another issue during the make install : 

```
/usr/bin/install -c taggerUpload.pl /data/moloch/bin
/usr/bin/install -c *.so *.jade *.js /data/moloch/plugins
/usr/bin/install -c wiseService/*.js wiseService/wiseService.ini.sample wiseService/package.json /data/moloch/wiseService
(cd /data/moloch/wiseService ; npm update)
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-01T22_00_38_515Z-debug.log
make[2]: *** [Makefile:27: install] Error 1

```

**Comment by awick** [comment]
Need to see /root/.npm/_logs/2018-03-01T22_00_38_515Z-debug.log, usually this is because you aren't actually using node 6

**Comment by 2Belette** [comment]
you're right I am on an lts version of node..
info using npm@5.3.0
info using node@v4.8.0

**Comment by 2Belette** [comment]
I updated to node v7.10.0 and now I got this error:

```
 CXX(target) Release/obj.target/png/src/common.o
  CXX(target) Release/obj.target/png/src/png_encoder.o
  CXX(target) Release/obj.target/png/src/png.o
../src/png.cpp: In member function ‘v8::Handle<v8::Value> Png::PngEncodeSync()’:
../src/png.cpp:33:71: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
     Local<Value> buf_val = Local<Object>::New(isolate, persistent())->GetHiddenValue(String::NewFromUtf8(isolate, "buffer"));
                                                                       ^~~~~~~~~~~~~~
../src/png.cpp: In static member function ‘static void Png::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/png.cpp:155:53: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’; did you mean ‘IntegerValue’?
     Local<Object>::New(isolate, png->persistent())->SetHiddenValue(String::NewFromUtf8(isolate, "buffer"), args[0]);
                                                     ^~~~~~~~~~~~~~
../src/png.cpp: In static member function ‘static void Png::UV_PngEncodeAfter(uv_work_t*)’:
../src/png.cpp:214:14: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declaration ]
     TryCatch try_catch; // don't quite see the necessity of this
              ^~~~~~~~~
In file included from /moloch/viewer/node_modules/png/.node-gyp/7.10.0/include/node/v8.h:26:0,
                 from /moloch/viewer/node_modules/png/.node-gyp/7.10.0/include/node/node.h:42,
                 from ../src/common.h:4,
                 from ../src/png.cpp:3:
/moloch/viewer/node_modules/png/.node-gyp/7.10.0/include/node/v8.h:7616:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/moloch/viewer/node_modules/png/.node-gyp/7.10.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/png.cpp:219:33: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
         FatalException(try_catch);
                                 ^
In file included from ../src/common.h:4:0,
                 from ../src/png.cpp:3:
/moloch/viewer/node_modules/png/.node-gyp/7.10.0/include/node/node.h:301:29: note: declared here
                 inline void FatalException(const v8::TryCatch& try_catch) {
                             ^
/moloch/viewer/node_modules/png/.node-gyp/7.10.0/include/node/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../src/png.cpp: In static member function ‘static void Png::PngEncodeAsync(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/png.cpp:264:76: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
     Local<Value> buf_val = Local<Object>::New(isolate, png->persistent())->GetHiddenValue(String::NewFromUtf8(isolate, "buffer"));
                                                                            ^~~~~~~~~~~~~~
make[2]: *** [png.target.mk:93: Release/obj.target/png/src/png.o] Error 1
make[2]: Leaving directory '/moloch/viewer/node_modules/png/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.37-gnu-1-lts
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /moloch/viewer/node_modules/png
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! png@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the png@3.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs png
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls png
make[1]: *** [Makefile:14: install] Error 1
make: *** [Makefile:326: install-recursive] Error 1

```

**Comment by awick** [comment]
png isn't actually required, it shouldn't matter if it works or not
You should be using node 6 with 0.50.  Its actually probably already installed in /data/moloch/bin if you add that to your path

**Comment by 2Belette** [comment]
I see `node-v6.12.3-linux-x64.tar.xz` in moloch path, I have untarred it and did an `PATH=$PATH:/softwares/moloch/node-v6.12.3-linux-x64/bin/` and` export PATH` and re-run `make install `but it seems it doesn't use the node from here :(

**Comment by awick** [comment]
It must be first in your path, not last.
